### ISSUE TITLE
Sketch 3.6.1 compatibility

### ISSUE THREAD

**Issue by matejgru** [kristof/sketch-i18n#5]
The plugin seems not to work with the lates version of Sketch. I have 3.6.1 installed and when I use 1. Generate, it does not put any text in the clipboard. Is there an update planed to make it work with the current versions? Otherwise an awesome plug-in.

Tnx!

Matej

**Comment by kristof** [comment]
Hi Matej, I'm not having this issue on 3.6.1, could you give some more info on OS version, etc? So I can try to reproduce the issue. (I've tested on Version 3.6.1 (26313), OSX 10.10.5)

Thanks,
Kristof

**Comment by matejgru** [comment]
Ok, tnx for the quick reply :)

I’ll try to recap:

I’m on a mac book pro
El Capitan 10.11.2 (15C50)
Sketch 3.6.1 (looks like its the current version, I checked updates)

I attached an example of page I want to translate. I tried it also with this test version and it also does not copy any text.
Also attaching a list of plugins I have. Maybe it helps.

I select the page and go to Plugins > 1. Generate…  and than try to paste it into TextMate.

Tnx for the quick response and help!

Matej

**Comment by kristof** [comment]
It is indeed the latest version of Sketch, the only difference I spot is that I'm still on Yosemite. I'll give it a go on El Capitan might be that the copy to clipboard functionality breaks on that OS version.

Kind regards,
Kristof

**Comment by matejgru** [comment]
Tnx for the help! appreciate it a lot.

Hope we find the issue and can improve for everybody else also. I don’t see what else could interfere this, but I will play a little more aroud also. Lets see.

Tnx!

Matej

**Comment by matejgru** [comment]
I copied the plugins again in the plug-in folder and it works now. Maybe it was something with the translate.js that was conflicting or the library folder. I think I had one before in the plug-in folder.
Works now! Thanks for your time and help Krsitof! 

Matej

**Comment by kristof** [comment]
Great, you're welcome!
